WSTemplateFormatVersion: 2010-09-09
Description: Peoplesoft92 ALB WAF
Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: Peoplesoft92-WAF
      Scope: REGIONAL
      Description: This is the Peoplesoft92 ALB WAF
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: Peoplesoft92-ALB-WAF
      Rules:
        - Name: F5-OWASP_Managed
          Priority: 0
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: F5-OWASP_Managed
          Statement:
            ManagedRuleGroupStatement:
              VendorName: F5
              Name: OWASP_Managed
  WebACLAssociation:
      Type: AWS::WAFv2::WebACLAssociation
      Properties: 
        ResourceArn: arn:aws:elasticloadbalancing:us-east-1:420417608870:loadbalancer/app/WAF-testing/b9472e166cbf817c 
        WebACLArn: !Ref WebACL
              
              
